[package]
name = "canonicalize-pathvar"
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
edition = "2018"

[[bin]]
name = "canonicalize-pathvar"
path = "main.rs"

[dependencies]
getopts = "0.2.19"
