#!/usr/bin/env bash

which pyenv 1>/dev/null 2>/dev/null || exit 0

. $HOME/dotfiles/shell/colors.include

version=$(pyenv version-name)
if [[ "$version" != 'system' ]]; then
    echo -n "(${cyan}$version${none}${bold}) ${none}"
fi
