#!/bin/sh

if [ x"$1" == x ]; then
	echo >&2 "Please specify a thing to install."
	exit 1
fi

if ! [ -e "$1" ]; then
	echo >&2 "That can't be installed."
	exit 1
fi

if [ "$1" == metadata ]; then
	echo >&2 "That can't be installed."
	exit 1
fi

name=${1%/}
target=$(head -n1 metadata/$name)

echo -ne '\033[0;33m'
tail -n+2 metadata/$name
echo -ne '\033[0m'

read -p "Are you sure? (Last chance to Ctrl-C) " -r
stow "-t$target" $name
